# Generated by Django 5.1.1 on 2024-09-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre_movie_yar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='yar',
            new_name='year',
        ),
    ]
